### ISSUE TITLE
antd缺陷----输入框的清除按钮默认有白色四方四正的底块

### ISSUE THREAD

**Issue by bigbigDreamer** [bigbigDreamer/FCC_Record#13]
# antd缺陷----输入框的清除按钮默认有白色四方四正的底块

## How To Reslove？

`Don't Worry!!!! `，我们可以操控这个类` .ant-select-selection__clear`

```css
   .ant-select-selection__clear {
            width: 16px;
            height: 16px;
            border-radius: 50%;
        }
```

没错，给予`border-radius： 50%`完美解决。
